name: Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        pip3 install pytest
        pip3 install pytest-cov
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pytest --cov . --cov-report xml:/home/runner/coverage.xml
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /home/runner/coverage.xml
          fail_ci_if_error: true
          verbose: true