name: Flake8

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v1
    - name: Flake8 Code Linter
      uses: jonasrk/flake8-action@master
      with: 
        args: "--exclude rich test"